language: r
sudo: false
cache: packages
warnings_are_errors: false

before_isntall:
  - Rscript -e 'install.packages(c("nlme","relax","car","FSA"), lib="/home/travis/R-bin/lib/R/library/")'

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
